### ISSUE TITLE
Could someone tell me how to use this mod?

### ISSUE THREAD

**Issue by PalePyth** [XDjackieXD/OpenRadio#10]
Thanks!

**Comment by XDjackieXD** [comment]
Define "how to use" :P
If you mean what you can do with the lasers: you can plug them into OpenComputers networks and use them to bridge 2 or more networks and using AEEncoders you can also bridge Applied Energistics 2 networks.

**Comment by polyzium** [comment]
But how to receive signals? I couldn't find any "receiver" thing or something like that
