### ISSUE TITLE
java.lang.IllegalArgumentException: Duplicate id: laser

### ISSUE THREAD

**Issue by cauliflower69** [XDjackieXD/OpenRadio#12]
After updating McJty mods your mod is crashing

https://github.com/McJty/McJtyLib/issues/11

**Comment by Kilobyte22** [comment]
Would be nice if you were to actually include an error log next time.

**Comment by XDjackieXD** [comment]
I will release a new hotfix version (0.7.3) now that fixes this.
On the other hand this means that some other mod did also register his tileentity as "laser" without a modid.

**Comment by XDjackieXD** [comment]
@Kilobyte22 look at the linked issue
