### ISSUE TITLE
AAAAAAAAAAAAAAAAAAAH EVERYTHING IS BROKEN HELP MEH

### ISSUE THREAD

**Issue by Ellpeck** [XDjackieXD/OpenRadio#4]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH

**Comment by XDjackieXD** [comment]
AAAAAHHHHHHHHHHHHHHHHHHHHH THEN FIX IT! :D

**Comment by Ellpeck** [comment]
NOOOOOOOO I CANT ITS YOUR MOD HELP

**Comment by XDjackieXD** [comment]
BUT... BUT... BUT...
clone the repo and run `git rm *`, `git commit -m "fixed stuff"` and finally `rm -rf *` !
should fix your problems!

**Comment by cyboerg42** [comment]
AHHHHHHHHHHH WHY!

**Comment by norpol** [comment]
Because of the [International Caps Lock Day](https://en.wikipedia.org/wiki/Caps_lock#International_Caps_Lock_Day).

**Comment by XDjackieXD** [comment]
@cyborg00222 NOW START LOOKING INTO MC MODDING AND HELP MEEEEE!
enough caps lock for the next few months :3

**Comment by Ellpeck** [comment]
AAAAAAAAAAAAH

**Comment by XDjackieXD** [comment]
HAAAAAAAAAAA
