### ISSUE TITLE
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

### ISSUE THREAD

**Issue by Ellpeck** [XDjackieXD/OpenRadio#9]
WHYYYY

**Comment by XDjackieXD** [comment]
BECAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUSE

**Comment by Ellpeck** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by norpol** [comment]
B..., Bu..., But the next international capslock day is on 28th June :(.
